[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@8.15.1 --activate", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"