[phases.setup]
nixPkgs = ["...", "nodejs-20_x", "pnpm-8_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "cd apps/web && pnpm start"