[phases.setup]
nixPkgs = ["...", "nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@8.24.1", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "cd apps/web && npm start"